# List of mock products available in the store
products = [
    {"id": 1, "name": "Wireless Mouse", "price": 499},
    {"id": 2, "name": "Mechanical Keyboard", "price": 1999},
    {"id": 3, "name": "Gaming Headphones", "price": 1499},
    {"id": 4, "name": "USB-C Hub", "price": 899},
    {"id": 5, "name": "Smart Watch", "price": 2999},
    {"id": 6, "name": "Portable SSD 1TB", "price": 5499},
    {"id": 7, "name": "Laptop Stand", "price": 1299},
    {"id": 8, "name": "Ergonomic Mouse Pad", "price": 399},
    {"id": 9, "name": "HD Web Camera 1080p", "price": 2499},
    {"id": 10, "name": "Wireless Charger Stand", "price": 1799},
    {"id": 11, "name": "Bluetooth Speaker", "price": 2199},
    {"id": 12, "name": "Noise Cancelling Earbuds", "price": 3499},
    {"id": 13, "name": "Mechanical Gaming Mouse", "price": 1899},
    {"id": 14, "name": "Adjustable Monitor Arm", "price": 3299},
    {"id": 15, "name": "Desk Mat Extra Large", "price": 899},
    {"id": 16, "name": "RGB LED Light Strip", "price": 1199},
    {"id": 17, "name": "Aluminum Headphone Stand", "price": 1499},
    {"id": 18, "name": "Cable Management Sleeve", "price": 499},
    {"id": 19, "name": "USB Microphone Kit", "price": 2799},
    {"id": 20, "name": "Portable Monitor 15.6 Inch", "price": 8999},
    {"id": 21, "name": "Desk Fan USB Powered", "price": 799},
    {"id": 22, "name": "Screen Light Bar", "price": 2299},
    {"id": 23, "name": "Smart Desk Lamp", "price": 1999},
    {"id": 24, "name": "Wireless Presenter Clicker", "price": 999},
    {"id": 25, "name": "Smart Plug Wi-Fi", "price": 799},
    {"id": 26, "name": "Smart Fitness Band", "price": 2499},
    {"id": 27, "name": "Portable Power Bank 20000mAh", "price": 1999},
    {"id": 28, "name": "Magnetic Phone Mount", "price": 599},
    {"id": 29, "name": "Foldable Laptop Desk", "price": 1499},
    {"id": 30, "name": "USB Desk Fan Oscillating", "price": 1199},
    {"id": 31, "name": "Wireless Bluetooth Earbuds Pro", "price": 4999},
    {"id": 32, "name": "Mechanical Keycaps Set", "price": 1299},
    {"id": 33, "name": "Desk Organizer Tray", "price": 899},
    {"id": 34, "name": "Smart Temperature Mug", "price": 2999},
    {"id": 35, "name": "Wireless Gaming Controller", "price": 3199},
    {"id": 36, "name": "Adjustable Phone Stand", "price": 499},
    {"id": 37, "name": "Braided USB-C Cable 2M", "price": 399},
    {"id": 38, "name": "Vertical Ergonomic Mouse", "price": 1599},
]